#pragma config(Sensor, dgtl2,  irLeft,         sensorDigitalIn)
#pragma config(Sensor, dgtl3,  irRight,        sensorDigitalIn)
#pragma config(Motor,  port2,           motorLeft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           motorRight,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int getIrReading(tSensors irReceiverPin)
{
		wait1Msec(1);
		int ir = SensorValue[irReceiverPin];
		wait1Msec(1);
		return ir;
}

task main()
{
	while (true)
	{
		if (vexRT[Btn8D] == 1)
		{
			while (true)
			{
				if (getIrReading(irLeft) == 1 && getIrReading(irRight) == 1)
				{
					motor[motorLeft] = 100;
					motor[motorRight] = -100;
				}
				else if (getIrReading(irLeft) == 0)
				{
					motor[motorLeft] = -50;
					motor[motorRight] = -50;
				}
				else if (getIrReading(irRight) == 0)
				{
					motor[motorLeft] = 50;
					motor[motorRight] = 50;
				}
				else {
					motor[motorLeft] = 0;
					motor[motorRight] = 0;
				}
			}
		}
	}
}
