#pragma config(Sensor, dgtl2,  irLeft,         sensorDigitalIn)
#pragma config(Sensor, dgtl3,  irMiddle,       sensorDigitalIn)
#pragma config(Sensor, dgtl4,  irRight,        sensorDigitalIn)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// used http://www.robotc.net/w/index.php?title=Tutorials/Arduino_Projects/Mobile_Robotics/BoeBot/Using_an_IR_sensor_to_detect_objects&oldid=6588


// function to get ir readings
int getIrReading(tSensors irReceiverPin)
{
		wait1Msec(1);
		int ir = SensorValue[irReceiverPin];
		wait1Msec(1);
		return ir;
}

task main()
{
	while (true)
	{
		// autonomous movement
		if (vexRT[Btn8D] == 1)
		{
			while (true)
			{
				if (getIrReading(irMiddle) == 0 && getIrReading(irLeft) == 0 && getIrReading(irRight) == 0)
				{
					motor[leftMotor] = 100;
					motor[rightMotor] = -100;
				}
				else if (getIrReading(irLeft) == 1)
				{
					while (getIrReading(irMiddle) == 1)
					{
						motor[leftMotor] = -50;
						motor[rightMotor] = -50;
					}
				}
				else if (getIrReading(irRight) == 1)
				{
					while (getIrReading(irMiddle) == 1)
					{
						motor[leftMotor] = 50;
						motor[rightMotor] = 50;
					}
				}
				else
				{
					motor[leftMotor] = 0;
					motor[rightMotor] = 0;
				}
			}
		}
	}
}
