#pragma config(Sensor, dgtl5,  irSensor,       sensorDigitalIn)
#pragma config(Motor,  port2,           motor1,        tmotorVex393_HBridge, openLoop, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int getIrReading(tSensors irReceiverPin)
{
		wait1Msec(1);
		int ir = SensorValue[irReceiverPin];
		wait1Msec(1);
		return ir;
}

task main()
{
	while(true){
		if (getIrReading(irSensor) < 0.5)
		{
				motor[motor1] = 100;
		}
		else
		{
			motor[motor1] = 0;
		}
	}
}
